### ISSUE TITLE
Issue with typing

### ISSUE THREAD

**Issue by tommycw1** [engrbm87/notifications_android_tv#4]
Just installed this using pip3:

```
$sudo pip3 install notifications-android-tv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting notifications-android-tv
  Downloading https://files.pythonhosted.org/packages/51/c5/22437492cf30713dd43697f5b5b05b5037dae380473bf2365d7ba79732ea/notifications_android_tv-0.1.3-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from notifications-android-tv) (2.21.0)
Installing collected packages: notifications-android-tv
Successfully installed notifications-android-tv-0.1.3
```

Next I created a small file using the example from your site as a proof of concept

```
#!/usr/bin/python3
  
from notifications_android_tv import Notifications

notify = Notifications("192.168.1.11")
notify.send(
    "message text",
    title="Title text",
    fontsize="medium",
    bkgcolor="green"
```
Made it executable and executed it.  I'm getting the following error:
```
$ ./nfa.py 
Traceback (most recent call last):
  File "./nfa.py", line 3, in <module>
    from notifications_android_tv import Notifications
  File "/usr/local/lib/python3.7/dist-packages/notifications_android_tv/__init__.py", line 2, in <module>
    from .notifications import Notifications
  File "/usr/local/lib/python3.7/dist-packages/notifications_android_tv/notifications.py", line 4, in <module>
    from typing import Final
ImportError: cannot import name 'Final' from 'typing' (/usr/lib/python3.7/typing.py)
```
I'm on:
```
$ python3 --version
Python 3.7.3
```
running on Raspberry pi 3:

```
$ uname -m
armv7l
```

On Raspbian GNU/Linux 10 (buster)

Any help to debug would be appreciated!

**Comment by tkdrob** [comment]
This might be an issue with your python version. Please try a higher version.

**Comment by tommycw1** [comment]
Thanks. Do you have a recommended version?

**Comment by tkdrob** [comment]
3.10 is out and it's stable.

**Comment by tommycw1** [comment]
@tkdrob OK, I've installed 3.10.2 and now this installed just fine.  Confirmed that it works.  Googling around it seems that it may only work with Python >=3.8.  You may want to confirm and add a note to your docs.

Thank for creating this module and your support!  I had been relying on a Go project to send these notifications and that project seems to no longer be supported.  Glad to have this much easier to work with python module!

**Comment by tkdrob** [comment]
It's actually not mine but I'll have to open a PR.

**Comment by tommycw1** [comment]
@tkdrob 

I see now that this ins't your project.  Thanks for your help on this, and the PR!
